/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './resources/**/*.blade.php',
    './resources/**/*.js',
    './app/**/*.php',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#00419d',
        'surface-container-low': '#f3f4f6',
        'on-error-container': '#93000a',
        'error': '#ba1a1a',
        'on-tertiary-container': '#ffa884',
        'surface-bright': '#f8f9fb',
        'primary': '#00317b',
        'surface': '#f8f9fb',
        'on-primary-fixed': '#001946',
        'surface-variant': '#e1e2e4',
        'tertiary-container': '#873000',
        'surface-container-high': '#e7e8ea',
        'outline': '#737784',
        'surface-tint': '#285ab9',
        'on-secondary-container': '#f9f7ff',
        'inverse-on-surface': '#f0f1f3',
        'primary-fixed': '#d9e2ff',
        'inverse-primary': '#b1c6ff',
        'on-tertiary-fixed': '#360f00',
        'on-secondary-fixed': '#00184a',
        'on-background': '#191c1e',
        'on-tertiary-fixed-variant': '#7e2c00',
        'inverse-surface': '#2e3132',
        'error-container': '#ffdad6',
        'on-primary-container': '#a3bcff',
        'tertiary': '#622000',
        'primary-container': '#0747a6',
        'outline-variant': '#c3c6d4',
        'secondary': '#0050cd',
        'on-surface-variant': '#434652',
        'background': '#f8f9fb',
        'surface-container': '#edeef0',
        'surface-container-highest': '#e1e2e4',
        'primary-fixed-dim': '#b1c6ff',
        'on-primary': '#ffffff',
        'on-surface': '#191c1e',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#dbe1ff',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#003fa5',
        'tertiary-fixed-dim': '#ffb598',
        'secondary-fixed-dim': '#b3c5ff',
        'tertiary-fixed': '#ffdbcd',
        'surface-dim': '#d9dadc',
        'secondary-container': '#0866ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '0.5rem',
        'stack-lg': '1.5rem',
        'gutter': '1.5rem',
        'header-height': '64px',
        'container-padding': '2rem',
        'sidebar-width': '260px',
        'stack-md': '1rem',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'table-header': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'table-header': ['12px', { lineHeight: '16px', fontWeight: '700' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};